### ISSUE TITLE
DREDD Ignores False #if Directives, Potentially Resulting In Invalid Code During Compilation

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#201]
**Steps To Reproduce:**
```
int main() {
    int foo;
    foo = 1
    #if BAR
        | 19
    #endif
        ;
}
```
After running DREDD on the above file(named `baz.c`), compiling with `clang baz.c -DBAR` results in syntax error.

**Comment by afd** [comment]
This is actually expected behaviour. At mutation time, Dredd accepts a compilation database, specifying which compiler options - such as -D and -I options - should be used to process the source file. It processes the source file in the context of those options, and thus mutates for one particular set of preprocessor symbols.

You cannot later compile the mutated code with different preprocessor symbols.

This is a good post on compilation databases:

https://eli.thegreenplace.net/2014/05/21/compilation-databases-for-clang-based-tools
