### ISSUE TITLE
dredd Incorrectly Handles Macro Expansion

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#239]
## Minimal Reproducible Example
```
#define BEGIN x = 

int main() {
  int x, y;
  BEGIN(y);
}
```

## dredd output
```
/* DREDD PRELUDE */

#define BEGIN x = 

int main() {
  int x, y;
  if (!__dredd_enabled_mutation(6)) { BEGIN__dredd_replace_expr_int((y), 0); }
}
```
where `BEGIN__dredd_replace_expr_int` causes an error.

**Comment by afd** [comment]
Dredd is doing the right thing here, except that it needs to insert a space before `__dredd_replace_expr_int`, because otherwise this is immediately preceded by the `BEGIN` token.

A solution would be to find the source location `loc` immediately preceding the begin source location for the `(y)` expression, and if `loc` is found not to be in the main source file (which is deemed to be the case for macros) to insert a space.

Another solution would be to always insert a space, but that would seem like overkill.

I'll look into the first.
