### ISSUE TITLE
Dredd injects prelude between function declaration keywords

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#322]
dredd mutates
```
class foo {
public:
  virtual void bar() const = 0;
};

class a : foo {
  void bar() const override;
};

void a::bar() const {
  int x = 2;
}
```
to
```
class foo {
public:
  virtual void bar() const = 0;
};

class a : foo {
  void bar() const #include <cinttypes>
###### PRELUDE #########
```

**Comment by afd** [comment]
It seems that this is due to a bug in the `getAssociatedRange` function in [SourceCode.cpp](https://clang.llvm.org/doxygen/SourceCode_8cpp_source.html#l00412).

The problem is that this function tries to extend a range to include attribubutes.

The `bar` function has the `override` attribute because this is specified in the function prototype.

However, the out-of-line declaration of this function does not have the attribute as part of its declaration. The `getAssociatedRange` function extends the range to right before the `override` token in the class version of the function, which is not correct.

**Comment by afd** [comment]
A similar issue arises with this:

```
class foo {
public:
  [[nodiscard]] int bar();
};

int foo::bar() {
  return 2;
}
```

The `[[nodiscard]]` in the class, but not the out-of-line declaration, leads to the wrong extended range.

**Comment by afd** [comment]
It looks like `isInherited` could be queried on an attribute to see whether it is inherited from another declaration or not. [See here](https://clang.llvm.org/doxygen/classclang_1_1Attr.html#ab45e2c3967694083935cd40cd92c5f5e).

This would require a patch to `getAssociatedRange`.

**Comment by afd** [comment]
@JonathanFoo0523 I suppose #336 will also resolve this issue.

**Comment by afd** [comment]
@JonathanFoo0523 Do you agree that we can close this now?

**Comment by JonathanFoo0523** [comment]
Agree. Closing this...
