### ISSUE TITLE
Insert prelude at beginning of file to minimise manual modifications

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#333]
The current prelude-injection behavior leads to many files requiring manual modification with:

```cpp
void __dredd_prelude_start();
```

Almost all source files with `override` class function modifiers fail without this manual modification, which is quite common. 

I believe we could reduce the need for manual changes by inserting the prelude at the very beginning of the file. Only a few cases, such as #302, wouldn't work with this approach, but I think those cases are rare.

**Comment by afd** [comment]
@JonathanFoo0523 can you look at the  diff between 24d06da1f9d09cf262ba90a2ce917f9544ac4915 and 6596515d0adf711dba7ef432439fa8b28705bc69 ?

This is a commit from James that introduced smarter logic to place the prelude, because of cases where the start of the function doesn't work, such as #215 and #219.

However, if the new `__dredd_prelude_start()` feature would take care of cases like that then I agree that it would be sensible to go back to the "beginning of file" approach.

If so then can you have a go at implementing it, by looking at how things worked back in 6596515d0adf711dba7ef432439fa8b28705bc69 ?
