### ISSUE TITLE
Header consistency in dredd's default and mutant-tracking modes

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#342]
Dredd uses different sets of headers for default mode and mutant-tracking mode. Since Dredd's headers are inserted at the beginning of the source file, they can "hide" the original program's headers and alter the definition of certain macros as described [here](https://github.com/mc-imperial/dredd/issues/341). As a result, the macro definitions may differ between default mode and mutant-tracking mode. Additionally, there might be cases where `void __dredd_prelude_start();` is required in one mode but not in the other.

To ensure consistency, Dredd should emit the union of #include headers from both modes.

**Comment by afd** [comment]
For the issue under Windows - if the experimental C11 atomics flag won't work it would be reasonable to guard the troublesome include lines with

#ifndef _MSC_VER
#include ...
#endif

This would skip it under Windows. Since mutant tracking presumably doesn't work under Windows at present, this would not make things any worse.

**Comment by afd** [comment]
But actually, see https://github.com/mc-imperial/dredd/pull/343#issuecomment-2366308199
