### ISSUE TITLE
How to handle a build process where a source file is compiled twice with different set of compilation flags?

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#347]
While mutating a source file for GCC-14.1.0, I encountered a file that is compiled twice with different configurations as part of the build process. There are two entries for that file in the compilation database. Since dredd's output is based on only one configuration (one set of compilation flags), the mutated source code fail the build process.

Is there a way to deal with this type of issue, other than not mutating files with more than 1 entry in compilation database?

**Comment by afd** [comment]
I can't think of any way to deal with this sort of issue automatically. Furthermore, it's quite common for a file to be in a compilation database multiple times in a harmless way, if the build configuration has generated steps for various types of builds - e.g. some libraries can be built in static or shared mode, and a file may occur twice due to this (so skipping such files by default probably would not be good).

Of course, one could manually duplicate the file and change the build system so that it refers to different versions of the file, but that gets rather intrusive and project specific.

For GCC I suggest just skipping this file (unless it looks like a critically interesting one).

In terms of closing out this issue, I suggest we add a note on this under "Troubleshooting" in the README. Feel free to take a first cut at that, or I can do it in due course.

**Comment by afd** [comment]
Closing this as your PR does a good job of explaining the problem, and there's no other action to take.
